// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv3uHrQFRBsT3Vqp3_SlYAg8lMF1CPGdY',
    appId: '1:61325637241:web:a8808209cad2e59ad046a8',
    messagingSenderId: '61325637241',
    projectId: 'noteapp-d6eca',
    authDomain: 'noteapp-d6eca.firebaseapp.com',
    storageBucket: 'noteapp-d6eca.appspot.com',
    measurementId: 'G-Y8G8WFK63V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBREFxJTWFgyMRUvYQnN4RCMqw9utOlwVk',
    appId: '1:61325637241:android:90d72855ca6b2acbd046a8',
    messagingSenderId: '61325637241',
    projectId: 'noteapp-d6eca',
    storageBucket: 'noteapp-d6eca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_30K2uACR-UKQ7zTlYaRpONJRak5XLI',
    appId: '1:61325637241:ios:eabcfd73ae0021f5d046a8',
    messagingSenderId: '61325637241',
    projectId: 'noteapp-d6eca',
    storageBucket: 'noteapp-d6eca.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_30K2uACR-UKQ7zTlYaRpONJRak5XLI',
    appId: '1:61325637241:ios:eabcfd73ae0021f5d046a8',
    messagingSenderId: '61325637241',
    projectId: 'noteapp-d6eca',
    storageBucket: 'noteapp-d6eca.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv3uHrQFRBsT3Vqp3_SlYAg8lMF1CPGdY',
    appId: '1:61325637241:web:f3dc665e1062700fd046a8',
    messagingSenderId: '61325637241',
    projectId: 'noteapp-d6eca',
    authDomain: 'noteapp-d6eca.firebaseapp.com',
    storageBucket: 'noteapp-d6eca.appspot.com',
    measurementId: 'G-WYTHKLXC5B',
  );
}
